version: "3.3"

services:

  sandbox-python38:
    build:
      context: ..
      args:
        - SANDBOX_USER_UID=999
        - SANDBOX_DIR=/sandbox
      dockerfile: ./docker/Dockerfile
    container_name: sandbox-python38
    image: sandbox-python38
    volumes:
      - ../src:/app/src
      - import:/sandbox/import:ro
    ports:
      - "9001:9001"
    networks:
      - localhost
    environment:
      - SANDBOX_USER_UID=999
      - SANDBOX_DIR=/sandbox
    restart: on-failure
    command: gunicorn --pythonpath '/app/src' --bind 0:9001 app.main:app --reload -w 1

networks:
  localhost:
    external: true

volumes:
  import:
    external: true
